import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Nav from '../component/navbar'
import Footer from '../component/footer'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Nav/>
        this is about page
                <Footer/>


      </main>
        
    </div>
  )
}